//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webdiyer.AspNetCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MvcCorePagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcCorePagerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Webdiyer.AspNetCore.MvcCorePagerResources", typeof(MvcCorePagerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--MvcPagerCore v1.0 for ASP.NET Core MVC 1.1+ © 2017 Webdiyer (http://en.webdiyer.com)--&gt;.
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string FirstPageText {
            get {
                return ResourceManager.GetString("FirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index is invalid.
        /// </summary>
        internal static string InvalidPageIndexErrorMessage {
            get {
                return ResourceManager.GetString("InvalidPageIndexErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string LastPageText {
            get {
                return ResourceManager.GetString("LastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index is out of range.
        /// </summary>
        internal static string PageIndexOutOfRangeErrorMessage {
            get {
                return ResourceManager.GetString("PageIndexOutOfRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string PrevPageText {
            get {
                return ResourceManager.GetString("PrevPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name cannot be null or empty.
        /// </summary>
        internal static string TagNameCannotBeNull {
            get {
                return ResourceManager.GetString("TagNameCannotBeNull", resourceCulture);
            }
        }
    }
}
